# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Lunchelot
tagline:          'Wenn's um Dein Mittagessen geht'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://blog.lunchelot.de
baseurl:          /

author:
  name:           'Lunchelot'
  url:            https://lunchelot.de

paginate:         5

# Custom vars
version:          

github:
  repo:           
